# Generated by Django 3.0.6 on 2020-12-03 23:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_expense',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='daily_expense',
            name='daily_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='daily_expense',
            name='date_input',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='daily_expense',
            name='month',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_app.Month_Expense'),
        ),
        migrations.AddField(
            model_name='month_expense',
            name='month',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='month_expense',
            name='month_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='month_expense',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='month_expense',
            name='year',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_app.Year_Expense'),
        ),
        migrations.AddField(
            model_name='year_expense',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='year_expense',
            name='year_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
