# Generated by Django 3.0.6 on 2020-12-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_auto_20201213_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='year_expense',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
