# Generated by Django 3.0.6 on 2020-12-17 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_year_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_expense',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
