# Generated by Django 3.0.6 on 2020-11-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0006_year_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_expense',
            name='month',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='month_expense',
            name='year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='expense_app.Year_Expense'),
        ),
    ]
