# Generated by Django 3.0.6 on 2020-11-22 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0008_month_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month_expense',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='month_expense',
            name='year',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_app.Year_Expense'),
        ),
    ]
