# Generated by Django 3.0.6 on 2020-11-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0009_auto_20201122_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month_expense',
            name='user',
        ),
    ]
