# Generated by Django 3.0.6 on 2020-11-25 00:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0011_auto_20201124_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_expense',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='year_expense',
            name='year_slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
