# Generated by Django 3.0.6 on 2020-11-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0012_auto_20201125_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year_expense',
            name='year_slug',
        ),
    ]
