# Generated by Django 3.0.6 on 2020-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0014_year_expense_year_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_expense',
            name='month_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
